import type { Pick, Bet } from './types'

export const MOCK_PICKS: Pick[] = [
  {
    id: '1',
    sport: 'NFL',
    homeTeam: 'Kansas City Chiefs',
    awayTeam: 'Las Vegas Raiders',
    line: 'Chiefs -7.5',
    odds: '-110',
    confidence: 84,
    tier: 1,
    research: 'Chiefs have covered the spread in 7 of their last 9 home games vs. divisional opponents. Raiders missing 2 starting CBs. Mahomes 12-2 ATS vs. Raiders all time. Weather clear, dome advantage.',
    result: 'pending',
    gameDate: new Date().toISOString(),
  },
  {
    id: '2',
    sport: 'MLB',
    homeTeam: 'LA Dodgers',
    awayTeam: 'SF Giants',
    line: 'Dodgers ML',
    odds: '-155',
    confidence: 76,
    tier: 1,
    research: 'Ohtani posting .342 BA in last 10 games. Starter Yamamoto has 1.82 ERA at Dodger Stadium this season. Giants bullpen ranks 28th in ERA last 2 weeks. Strong matchup on paper.',
    result: 'pending',
    gameDate: new Date().toISOString(),
  },
  {
    id: '3',
    sport: 'Soccer',
    homeTeam: 'Real Madrid',
    awayTeam: 'Atletico Madrid',
    line: 'Real Madrid -0.5',
    odds: '+120',
    confidence: 63,
    tier: 2,
    research: 'Real Madrid unbeaten in last 14 home El Clasicos. Vinicius Jr. back from suspension. Atletico playing 3rd game in 8 days — fatigue factor significant. Bellingham expected to start.',
    result: 'pending',
    gameDate: new Date().toISOString(),
  },
  {
    id: '4',
    sport: 'NFL',
    homeTeam: 'San Francisco 49ers',
    awayTeam: 'Seattle Seahawks',
    line: '49ers -6',
    odds: '-110',
    confidence: 71,
    tier: 2,
    research: 'McCaffrey back at full health after bye week. 49ers have the best red zone offense in NFC. Seattle struggling to stop the run — 28th in rush defense DVOA. Rain in forecast favors ground game.',
    result: 'pending',
    gameDate: new Date().toISOString(),
  },
  {
    id: '5',
    sport: 'MLB',
    homeTeam: 'NY Yankees',
    awayTeam: 'Boston Red Sox',
    line: 'Over 9.5',
    odds: '-115',
    confidence: 58,
    tier: 3,
    research: 'Both bullpens are exhausted — combined 14 innings pitched in last 2 days. Wind blowing out to right field at 14 mph. Both starters have been shelled in their last 2 starts. High variance pick.',
    warning: 'High risk — both starters are unpredictable this week. Size down.',
    result: 'pending',
    gameDate: new Date().toISOString(),
    isWarning: false,
  },
  {
    id: '6',
    sport: 'Soccer',
    homeTeam: 'Manchester City',
    awayTeam: 'Arsenal',
    line: 'Man City -0.5',
    odds: '-130',
    confidence: 69,
    tier: 2,
    research: 'Man City unbeaten at the Etihad in their last 18 Premier League matches. Arsenal missing Saka and Odegaard through injury. Haaland scored in 5 consecutive home fixtures. Possession battle expected.',
    result: 'pending',
    gameDate: new Date().toISOString(),
  },
  {
    id: 'wc1',
    sport: 'World Cup',
    homeTeam: 'Germany',
    awayTeam: 'France',
    line: 'France ML',
    odds: '+110',
    confidence: 74,
    tier: 2,
    research: 'France have won 4 of last 5 meetings with Germany in tournament play. Mbappé fully fit and in form with 4 goals in 3 matches this tournament. Germany defense conceded 2+ in last 2 knockout games. Value on France at plus odds.',
    result: 'pending',
    gameDate: new Date().toISOString(),
  },
  {
    id: 'wc2',
    sport: 'World Cup',
    homeTeam: 'Spain',
    awayTeam: 'England',
    line: 'Over 2.5 Goals',
    odds: '-115',
    confidence: 78,
    tier: 1,
    research: 'Over 2.5 has hit in 9 of Spain\'s last 11 tournament games. England averaging 2.8 goals per game this WC. Both teams pressing high and creating 15+ chances per 90. Neutral venue removes home crowd factor.',
    result: 'pending',
    gameDate: new Date().toISOString(),
  },
  {
    id: 'wc3',
    sport: 'World Cup',
    homeTeam: 'Portugal',
    awayTeam: 'Morocco',
    line: 'Morocco +1.5',
    odds: '+145',
    confidence: 62,
    tier: 3,
    research: 'Morocco have covered +1.5 in every knockout match this tournament. Disciplined defensive shape conceding just 0.7 xGA per game. Portugal struggling to break down low blocks — 0 goals vs. defensive setups in last 3. Value underdog.',
    result: 'pending',
    gameDate: new Date().toISOString(),
  },
  {
    id: 'nba1',
    sport: 'NBA',
    homeTeam: 'Boston Celtics',
    awayTeam: 'Miami Heat',
    line: 'Celtics -8.5',
    odds: '-110',
    confidence: 80,
    tier: 1,
    research: 'Celtics 14-3 ATS at home this season, best mark in the NBA. Heat playing back-to-back, second night in Boston. Tatum averaging 34 points in last 5 home games. Miami shooting 31% from three on the road.',
    result: 'pending',
    gameDate: new Date().toISOString(),
  },
]

export const MOCK_WARNING: Pick = {
  id: 'w1',
  sport: 'NFL',
  homeTeam: 'Dallas Cowboys',
  awayTeam: 'Philadelphia Eagles',
  line: 'Eagles -3',
  odds: '-110',
  confidence: 42,
  tier: 3,
  research: 'Sharp money moving Cowboys +3 despite Eagles being favored. Key Cowboys players returning from injury. Line movement suspicious — possible sharp fade.',
  warning: '⚠️ DO NOT PARLAY — Public heavily on Eagles. Reverse line movement on Cowboys. Fade the public or sit this one out.',
  result: 'pending',
  gameDate: new Date(Date.now() + 86400000).toISOString(),
  isWarning: true,
}

export const MOCK_BETS: Bet[] = [
  { id: 'b1', sport: 'NFL', description: 'Chiefs -7.5', amount: 100, odds: '-110', tier: 1, result: 'win', payout: 190.9, createdAt: new Date(Date.now() - 86400000 * 6).toISOString() },
  { id: 'b2', sport: 'MLB', description: 'Dodgers ML', amount: 50, odds: '-150', tier: 1, result: 'win', payout: 83.3, createdAt: new Date(Date.now() - 86400000 * 5).toISOString() },
  { id: 'b3', sport: 'Soccer', description: 'Real Madrid -0.5', amount: 75, odds: '+120', tier: 2, result: 'loss', payout: 0, createdAt: new Date(Date.now() - 86400000 * 4).toISOString() },
  { id: 'b4', sport: 'NFL', description: '49ers -6', amount: 100, odds: '-110', tier: 2, result: 'win', payout: 190.9, createdAt: new Date(Date.now() - 86400000 * 3).toISOString() },
  { id: 'b5', sport: 'MLB', description: 'Yankees/Red Sox Over 9.5', amount: 50, odds: '-115', tier: 3, result: 'loss', payout: 0, createdAt: new Date(Date.now() - 86400000 * 2).toISOString() },
  { id: 'b6', sport: 'Soccer', description: 'Brazil vs Argentina BTTS', amount: 60, odds: '+105', tier: 2, result: 'win', payout: 123, createdAt: new Date(Date.now() - 86400000 * 1).toISOString() },
]
