import { NextRequest, NextResponse } from 'next/server'

const PLANS = {
  single:    { amount: 500, label: '1 Resume + Cover Letter' },
  bundle:    { amount: 2900, label: '5 Resume + Cover Letter Sets + LinkedIn Summary' },
  unlimited: { amount: 1900, label: 'Unlimited Resumes & Cover Letters (Monthly)' },
}

export async function POST(req: NextRequest) {
  if (!process.env.STRIPE_SECRET_KEY) {
    return NextResponse.json(
      { error: 'Payments are not configured yet. Add STRIPE_SECRET_KEY to your Vercel environment variables.' },
      { status: 503 }
    )
  }

  try {
    const Stripe = (await import('stripe')).default
    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY)

    const body = await req.json()
    const { plan = 'single', formData } = body
    const selected = PLANS[plan as keyof typeof PLANS] ?? PLANS.single
    const base = (process.env.NEXT_PUBLIC_BASE_URL ?? 'http://localhost:3000').replace(/\/$/, '')

    const session = await stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'usd',
            product_data: {
              name: `ResumeRocket — ${selected.label}`,
              description: 'ATS-optimized resume and cover letter, generated by AI in under 60 seconds.',
            },
            unit_amount: selected.amount,
          },
          quantity: 1,
        },
      ],
      mode: 'payment',
      success_url: `${base}/order/result?session_id={CHECKOUT_SESSION_ID}&plan=${plan}`,
      cancel_url: `${base}/order`,
    })

    // Save form data server-side so it survives browser/device changes
    if (formData && session.id && process.env.NEXT_PUBLIC_SUPABASE_URL) {
      try {
        const { getSupabase } = await import('@/lib/supabase')
        await getSupabase().from('pending_sessions').insert({
          stripe_session_id: session.id,
          form_data: formData,
        })
      } catch (e) {
        console.error('Failed to save form data to Supabase:', e)
        // Non-fatal — localStorage is the fallback
      }
    }

    return NextResponse.json({ url: session.url })
  } catch (error) {
    console.error('Checkout error:', error)
    const message = error instanceof Error ? error.message : 'Failed to create checkout session'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
